manifest:
  remotes:
    # zmk official
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # testing mouse keys
    - name: mousekeys
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 331915f98931308f49f43485c75f5d0c08f0cf29
      import: app/west.yml
  self:
    path: config
